# Generated by Django 5.1.4 on 2025-01-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание алкоголя')),
                ('data_purchase', models.DateField(verbose_name='Дата покупки')),
                ('data_bottling', models.DateField(blank=True, null=True, verbose_name='Дата розлива')),
                ('alcohol_retention', models.IntegerField(blank=True, max_length=2, null=True, verbose_name='Выдержка')),
                ('volume', models.IntegerField(max_length=3, verbose_name='Объем')),
                ('strength', models.IntegerField(max_length=2, verbose_name='Крепость')),
                ('country', models.CharField(max_length=255, verbose_name='Место производства')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Завод изготовитель')),
                ('price', models.IntegerField(verbose_name='Цена миньёна')),
                ('photo', models.BooleanField(default='нет', verbose_name='Фото')),
            ],
        ),
    ]
