# Generated by Django 5.1.4 on 2025-01-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minion',
            name='alcohol_retention',
            field=models.IntegerField(blank=True, null=True, verbose_name='Выдержка'),
        ),
        migrations.AlterField(
            model_name='minion',
            name='strength',
            field=models.IntegerField(verbose_name='Крепость'),
        ),
    ]
