# Generated by Django 5.1.4 on 2025-01-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0002_alter_minion_alcohol_retention_alter_minion_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minion',
            name='volume',
            field=models.IntegerField(verbose_name='Объем'),
        ),
    ]
