# Generated by Django 5.1.4 on 2025-01-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0005_alter_minion_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minion',
            name='photo',
            field=models.BooleanField(default=True, verbose_name='Фото'),
        ),
    ]
