# Generated by Django 5.1.4 on 2025-01-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0006_alter_minion_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minion',
            name='photo',
            field=models.BooleanField(default=False, verbose_name='Фото'),
        ),
    ]
