# Generated by Django 5.1.4 on 2025-01-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0007_alter_minion_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minion',
            options={'ordering': ['-data_purchase']},
        ),
        migrations.AddField(
            model_name='minion',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='minion',
            index=models.Index(fields=['-data_purchase'], name='bottle_mini_data_pu_dd3f37_idx'),
        ),
    ]
