# Generated by Django 5.1.4 on 2025-01-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0008_alter_minion_options_minion_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minion',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
