# Generated by Django 5.1.4 on 2025-01-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0009_alter_minion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minion',
            name='photo',
            field=models.BooleanField(choices=[(0, 'Нет фото'), (1, 'Есть фото')], default=0, verbose_name='Фото'),
        ),
    ]
