# Generated by Django 5.1.4 on 2025-01-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0011_category_minion_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minion',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bottle.category'),
        ),
    ]
