# Generated by Django 5.1.4 on 2025-01-23 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0012_alter_minion_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagMinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='minion',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minions', to='bottle.category'),
        ),
        migrations.AddField(
            model_name='minion',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='bottle.tagminion'),
        ),
    ]
