# Generated by Django 5.1.4 on 2025-01-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0013_tagminion_alter_minion_cat_minion_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minion',
            name='data_bottling',
        ),
        migrations.AddField(
            model_name='minion',
            name='date_reg',
            field=models.DateField(auto_now=True, verbose_name='Дата регистрации'),
        ),
    ]
