# Generated by Django 5.1.4 on 2025-01-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0014_remove_minion_data_bottling_minion_date_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='bottle.tagminion'),
        ),
    ]
