# Generated by Django 5.1.4 on 2025-01-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0016_bigminion_minion_bigminion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minion',
            name='date_reg',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата регистрации'),
        ),
    ]
