# Generated by Django 5.1.4 on 2025-01-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0018_alter_minion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagminion',
            name='char',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
