# Generated by Django 5.1.4 on 2025-01-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0019_tagminion_char'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagminion',
            name='char',
        ),
        migrations.AddField(
            model_name='bigminion',
            name='char',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
