# Generated by Django 5.1.4 on 2025-02-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0022_rename_photo_minion_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minion',
            name='is_active',
            field=models.BooleanField(choices=[(False, 'Не активный'), (True, 'Активный')], default=0, verbose_name=''),
        ),
    ]
