# Generated by Django 5.1.4 on 2025-02-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0024_minion_photo_alter_minion_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='minions', to='bottle.tagminion'),
        ),
    ]
