# Generated by Django 5.1.4 on 2025-02-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0025_alter_minion_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minion',
            name='is_active',
            field=models.BooleanField(choices=[(False, 'Не активный'), (True, 'Активный')], default=0, verbose_name='Стaтус'),
        ),
    ]
